language: node_js
node_js:
- '5'
script:
  - chmod +x dist_verifier.sh
  - ./dist_verifier.sh
deploy:
  - provider: releases
    api_key:
      secure: mobW3qI1QOMN6dZSbQRP3rUkEp3WnoUuaWL+Xwcmtb5Y8brV4ecVUG2/vUs3JP4dnAoPu/Pwo0TJ/3uK0r0sNjFdGnGCRAAPAjdJyPBoPFOGjvp4cO2Gt6qnHexE62getW84ZZwMj+DjUji1D4/uIlkzejuCVl5RIM/3iWTuQUMw5Byi71a4jK3F4lyu4ISsv7DhwyEnSfQadx7BPsLP1+jzfVTnMJcMNCER0XsESfmhnG2+xT8nJciyeGMnzUVM7A+HMD0Lu7DeCWk/7awkrG+OphQ8mYa7TPBRziwZw+rJiM6+E/P3+nWjOyneov58KTJ/3DrFMjSaqvftcUbAu2ItERGzuJWib8+LyB55TtHQdnwxPrVMtrNXjQL+73Oz535x2HcoFNu+KzlNzGLo2o5RHi4yRUuVPSNLDpRgj4R7/peJd0DIwY+QSFn5tRgUXZAnga8j/Y6dncRJEwTdWnGDiBgCzzOPnIDL96TbSRLgkIOr9TY4Y4zI9nOw74IIo2/UB0tcKXHBxrkFclFdnwc0zbjU+F5E4oo11KA/Dl3NBsqYY5el43aj+Uy96b9ue9F5ky8d9tc+0rP9O3Cs2oX7DdXOduqp6cop95miV+ZYU0A3VYGvee2ATkwvHBT3Ys/d4WroyBHWohkmP0+OH+7VY9Q7PE4UEyAzwDwVIrI=
    file: dist/*
    file_glob: true
    skip_cleanup: 'true'
    on:
      branch: master
      tags: true
  - provider: npm
    api_key:
      secure: AnBqHff9MZNlQ2ymKS6+HFMQq/TEykmxMjarcf2/Y+2Y2QP05uOWqxNQ3jp0mJfCfsM5u/bTCRIgjYBBRkQAkM/Tbn4rYTUpc0xUbskdl6W9ERIfOJDeZ7MYqE/wqLbSY/HBRZHxLvPSfp03rPdq45KKyN7wLenePo23Kb+JkKbSOSloiS2fcn+/hAcuoaED3vfDbPiPIkVrTv+rv2XVAFD94NwX+fjhE5f47nEUC4weRzPqdMsUEVU+ypvf915tCcooLP9tcep5jfVyj6PBTLXGy7u1WVOSfWFQ0wk5QDh9thk3lHw7kGCjSMfZ2cKCzuWNkbG3feTWgRqG8J9unQcocoqBW63LylKPVG0yjBQocjN4fG9+61ljkRhtHbuCxNQR6kOnHRDFuRf8xFhmUmFBlwHbrzxbTkVkTryD5oE5QvASi5BIQaFp1hTTnyMPhG+wybCDrKUAooZZFjCV5jTzRhsETBePFdyQUGs12AAXowOHCskdcwQRL+nSQnmsfXN/OJ4utk05Jt2Nr9HvDpZ0das3YlzSR47ShIkLbH0z3et16/HISQtt4hDa8cXZE5B39NDmvPztyKb7TM9pA68pLgU16xkiji10svNGkV1CMBZTbE1nQtvRQPNE4bS+xcV9+02qbT3elbfGieLuiKjBVl7en3c55Hsn5BMZ3Kk=
    email: mac89@hotmail.com
    skip_cleanup: 'true'
    on:
      branch: master
      tags: true